config/routes.rb
Myflix::Application.routes.draw do
  root to: 'pages#front'

  get 'ui(/:action)', controller: 'ui'

  resources :videos do
    collection do
      get 'search', to: 'videos#search'
    end

    resources :reviews, only: [:create,:edit,:update,:destroy]
  end

  namespace :admin do
    resources :videos
    resources :categories
  end

  resources :categories
  resources :users do
    resources :queue_items, only:[:index,:create,:destroy]
    post 'update_queue', to:'queue_items#update_queue'
    
    resources :friendships, only:[:index, :destroy,:create]
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
 
end

app/models/video.rb
class Video < ActiveRecord::Base
  include Slug

  validates_presence_of :title, :description
  belongs_to :category, foreign_key: :category_id
  has_many :reviews, -> {order 'created_at DESC'}, foreign_key: :video_id
  sluggable_column :title

  before_create :generate_slug

  has_many :queue_items, foreign_key: :video_id

  mount_uploader :small_cover, SmallCoverUploader
  mount_uploader :large_cover, LargeCoverUploader

  def self.search_by_title(title)
    where("title ILIKE ?", "%#{title}%").order("title ASC  ")
  end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < AdminsController
 before_action :select_video, only:[:edit,:update,:destroy] 
  def new
    @video = Video.new
    @categories = Category.all
  end

  def create
    @video = Video.new(video_params)
    if @video.save 
      flash["success"] = "Your video was successfully uploaded"
    else
      flash["danger"] = "There was a problem uploading that video"
    end

    redirect_to new_admin_video_path
  end

  def edit
    @categories = Category.all
  end

  def update
    if @video.update(video_params)
      flash["success"] = "Video was successfully edited"
      redirect_to video_path(@video)
    else
      flash.now["danger"] = "There was a problem updating this video"
      render :edit
    end
  end

  def destroy
    @video.destroy
    redirect_to videos_path
  end

  private
  def video_params
    params.require(:video).permit(:title,:description,:category_id,:small_cover,:large_cover,:video_url)
  end

  def select_video
    @video = Video.find_by(slug: params[:id])
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :require_user
  def index
    @categories = Category.all 
  end

  def show
    @video = Video.find_by(slug: params[:id])
    @review_total = @video.reviews.count
    @rating_average = @video.reviews.average("rating") if @video.reviews
    @review = Review.new
  end

  def search
    @videos = Video.search_by_title(params[:query])
  end

end

app/helpers/video_helper.rb
module VideoHelper
end

app/views/videos/_reviewform.html.haml
= bootstrap_form_for([@video,@review]) do |f|
  .row
    .col-sm-3
      =f.select :rating, rating_options, {label: "Rate this video", include_blank: true}
  .row
    .col-sm-7
      = f.text_area :content, label: "Write a review"
      = f.submit "Submit", class: "btn btn-small btn-success"  

app/views/videos/index.html.haml
%article.video_category
  %header
    -@categories.each do |category|
      %h3
        = link_to category.name, category
      %br
      .videos.row
        -category.recent_videos(4).each do |video|
          .video.col-sm-3
            =link_to video_path(video) do
              =image_tag(video.small_cover, size: "166x236")
              %p
                =video.title
      %br
      %hr

       

app/views/videos/search.html.haml
%br
.videos.row
  -@videos.each do |video|
    .video.col-sm-3
      =link_to video_path(video) do
        =image_tag(video.small_cover_url, size: '166x240')
      %br
      %hr

app/views/videos/show.html.haml
%article.video
  .container-fluid
    .row
      .video_large_cover.col-md-7.col-sm-offset-1  
        -if youtube?(@video)
          %iframe(width = "100%" height = "375" src = "#{@video.video_url}" frameborder = "0" allowfullscreen)
        -else
          %video(width = "100%" height = "375" controls src = "#{@video.video_url}" poster = "#{@video.large_cover}" Your browser does not support html5)
        
      .video_info.col-md-3
        %header
          %h3.lead 
          =@video.title 
          %br
          %span Rating: #{@rating_average} /5.0
          %br
          %span #{@review_total} reviews
        %p
        =@video.description
        %br
        %hr
        .actions
          -if !current_user.video_in_user_queue?(@video.id)
            =link_to "+My Queue", user_queue_items_path(current_user, video_id: @video.id), method: :post, class: "btn btn-success"
          -else
            %br 
            %br
            %p
              =link_to "Video Is In Your Queue", user_queue_items_path(current_user)
            %br
          - if current_user.admin
            %p 
              =link_to "Edit Video", edit_admin_video_path(@video)
            %p
              =link_to "Delete Video",admin_video_path(@video), method: :delete
              

%section.reviews.container
  .row
    .col-sm-10.col-sm-offset-1
      -if logged_in?
        = render 'reviewform' 
      %header
        %h3 User Reviews (#{@review_total}) 
      %ul
        - @video.reviews.first(8).each do |review|
          %article.review
            %li.row
              .col-sm-2
                %span Rating: #{review.rating}/ 5.0
                %p by 
                =link_to review.user.full_name, review.user
                %p.small 
                  on #{review.updated_at}
                %p
                  -if review.user ==current_user
                    =link_to "edit review", edit_video_review_path(@video,review)
                    %p
                    =link_to "delete review", video_review_path(@video,review), method: :delete

              .col-sm-8
                =review.content if review.content

                        