config/routes.rb
Myflix::Application.routes.draw do
  root to: 'pages#front'

  get 'ui(/:action)', controller: 'ui'

  resources :videos do
    collection do
      get 'search', to: 'videos#search'
    end

    resources :reviews, only: [:create,:edit,:update,:destroy]
  end

  namespace :admin do
    resources :videos
    resources :categories
  end

  resources :categories
  resources :users do
    resources :queue_items, only:[:index,:create,:destroy]
    post 'update_queue', to:'queue_items#update_queue'
    
    resources :friendships, only:[:index, :destroy,:create]
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
 
end

app/views/shared/_header.html.haml
%section#top-header.row
  %h1.col-md-2
    = link_to "BioFLiX", root_path
  - if logged_in?
    %ul.col-md-4.clearfix
      %li= link_to "Videos", videos_path
      %li= link_to "My Queue",user_queue_items_path(current_user)
      %li= link_to "People",user_friendships_path(current_user)
      - if current_user.admin
        %li= link_to "Admin Page", new_admin_video_path
    = form_tag search_videos_path, class: "span5 for-search" do
      %input.search-query(name="search_term" type="text" placeholder= "Search for videos here")
      %button.btn.shift_right(type="submit") Search
    #user_links.pull-right
      %ul
        %li.dropdown
          %a(href="#" id="dlabel" role="button" data-toggle="dropdown" class="dropdown-toggle" data-target="#")
            Welcome #{current_user.first_name}
            %b.caret
          %ul.dropdown-menu(role="menu" aria-labelledby="dlabel")
            %li
              %a(href="#") Account
              %a(href="#") Plan and Billing
              =link_to "Sign Out", logout_path

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  %div(class="alert alert-#{name}")
    %a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)