config/routes.rb
Myflix::Application.routes.draw do
  root to: 'pages#front'

  get 'ui(/:action)', controller: 'ui'

  resources :videos do
    collection do
      get 'search', to: 'videos#search'
    end

    resources :reviews, only: [:create,:edit,:update,:destroy]
  end

  namespace :admin do
    resources :videos
    resources :categories
  end

  resources :categories
  resources :users do
    resources :queue_items, only:[:index,:create,:destroy]
    post 'update_queue', to:'queue_items#update_queue'
    
    resources :friendships, only:[:index, :destroy,:create]
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
 
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :leader, class_name: "User", foreign_key: :leader_id
  belongs_to :follower, class_name: "User", foreign_key: :follower_id
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :require_user
  def index;end

  def create
    leader = User.find(params[:leader_id])
    if current_user == leader
      flash["danger"] = "You can't follow yourself"
      redirect_to user_path(current_user)
      return
    elsif current_user.follows?(leader)
      flash["danger"] = "You are already following #{leader.first_name}"
      redirect_to user_friendships_path(current_user)
      return
    else
      friendship = Friendship.new(leader: leader, follower: current_user) 
    end 

    if friendship.save
      flash["success"] = "You are now following #{friendship.leader.first_name}"
    else
      flash["danger"] = "There was an error following #{User.find(params[:leader_id])}"
    end

    redirect_to user_friendships_path(current_user)
  end

  def destroy
    relationship = Friendship.find(params[:id])
    relationship.destroy if relationship.follower == current_user
    redirect_to user_friendships_path(current_user)
  end
end

app/views/friendships/index.html.haml
%section.people
  %header
    %h2 People I Follow
  %table.table
    %thead
      %tr
        %th(width="30%")
        %th(width="20%") Videos in Queue
        %th(width="20%") Followers
        %th(width="30%") Unfollow
    %tbody
      - current_user.following_relationships.each do |relationship|
        %tr
          %td
            = link_to relationship.leader.full_name, relationship.leader
          %td.extra-padding 
            = relationship.leader.queue_items.count
          %td.extra-padding 
            = relationship.leader.leading_relationships.count
          %td.extra-padding
            = link_to user_friendship_path(current_user, relationship), method: :delete do
              %i.glyphicon.glyphicon-remove
  %br
  %br
  %br
  %br
  %hr
  %h3 Others Users You Can Follow
  %hr
  %ul
    -User.random_users.each do |user|
      %li
        = link_to user.full_name, user