config/routes.rb
Myflix::Application.routes.draw do
  root to: 'pages#front'

  get 'ui(/:action)', controller: 'ui'

  resources :videos do
    collection do
      get 'search', to: 'videos#search'
    end

    resources :reviews, only: [:create,:edit,:update,:destroy]
  end

  namespace :admin do
    resources :videos
    resources :categories
  end

  resources :categories
  resources :users do
    resources :queue_items, only:[:index,:create,:destroy]
    post 'update_queue', to:'queue_items#update_queue'
    
    resources :friendships, only:[:index, :destroy,:create]
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
 
end

app/models/category.rb
class Category < ActiveRecord::Base
  include Slug
  has_many :videos, foreign_key: :category_id
  sluggable_column :name

  before_create :generate_slug

  validates :name, uniqueness: true


  def recent_videos(number)
    ordered_videos = videos.order(created_at: :desc).first(number)
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminsController
  before_action :find_category, only:[:destroy,:edit,:update]

  def new
    @category = Category.new
    @all_categories = Category.all
  end

  def create
    category = Category.new(category_params)
    if category.save
      flash["success"] = "Category has been added"
    else
      flash["danger"] = "There was a problem adding that category"
    end
    redirect_to new_admin_category_path
  end

  def destroy
    @category.destroy
    redirect_to new_admin_category_path
  end

  def edit;end

  def update
    if @category.update(category_params)
      flash["success"] = "Category was successfully edited"
      redirect_to new_admin_category_path
    else
      flash.now["danger"] = "There was a problem updating this category"
      render 
    end

  end


  private
  def category_params
    params.require(:category).permit(:name)
  end

  def find_category
    @category = Category.find_by(slug: params[:id])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find_by(slug: params[:id])
  end
end

app/views/admin/categories/edit.html.haml
%section.admin_add_video
  .container
    .row
      .col-md-10.col-md-offset-1
      =render "admin/categories/shared/category", url: admin_category_path, method: "put"
        

app/views/admin/categories/new.html.haml
%section.admin_add_video
  .container
    .row
      .col-md-10.col-md-offset-1
        %ul.nav.nav-pills
          %li
            %a(href="/ui/admin_views_payments") Recent Payments
          %li
            =link_to "Add a New Video",new_admin_video_path
          %li.active
            =link_to "Add a Category", " "
        %br
        %hr
        =render "admin/categories/shared/category", url: admin_categories_path, method: "post"

        %br
        %hr
        %h3 Categories
        %hr
        %ul 
          -@all_categories.each do |category|
            %li
              ="#{category.name} (#{category.videos.count})" 
              =link_to "edit", edit_admin_category_path(category)
              =link_to "delete", admin_category_path(category), method: :delete, class: "shift_right"
              %hr
      
              